apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: demo
spec:
  replicas: 5
  selector:
    matchLabels: { app: loadgen }
  template:
    metadata:
      labels: { app: loadgen }
    spec:
      containers:
      - name: busybox
        image: busybox:1.36
        command: ["/bin/sh","-c"]
        args:
          - |
            while true; do
              wget -q -O- http://web.demo.svc.cluster.local >/dev/null 2>&1
            done
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "128Mi" }

