name: Terraform - GKE Infra

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

env:
  PROJECT_ID:      ${{ secrets.GCP_PROJECT_ID }}
  REGION:          ${{ secrets.GCP_REGION }}
  ZONE:            ${{ secrets.GCP_ZONE }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (GCS backend)
        run: |
          terraform -chdir=terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="prefix=gke/state"

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -var="project_id=${PROJECT_ID}" \
            -var="region=${REGION}" \
            -var="zone=${ZONE}" \
            -var="name=demo"

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="project_id=${PROJECT_ID}" \
            -var="region=${REGION}" \
            -var="zone=${ZONE}" \
            -var="name=demo"

      - name: Show Outputs
        run: terraform -chdir=terraform output -json

