name: Terraform Destroy - GKE Infra

on:
  workflow_dispatch:
    inputs:
      directory:
        description: "Terraform root directory"
        required: true
        default: terraform
      name:
        description: "Value for var.name"
        required: true
        default: demo
      confirm:
        description: "Type exactly: I UNDERSTAND THIS WILL DELETE RESOURCES"
        required: true
        default: ""

env:
  PROJECT_ID:      ${{ secrets.GCP_PROJECT_ID }}
  REGION:          ${{ secrets.GCP_REGION }}
  ZONE:            ${{ secrets.GCP_ZONE }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

permissions:
  contents: read

jobs:
  plan:
    name: Plan (destroy)
    runs-on: ubuntu-latest
    env:
      DIR:  ${{ github.event.inputs.directory }}
      NAME: ${{ github.event.inputs.name }}
    steps:
      - name: Validate confirmation
        run: |
          if ! echo "${{ github.event.inputs.confirm }}" | grep -q '^I UNDERSTAND THIS WILL DELETE RESOURCES$'; then
            echo "::error::Confirmation text mismatch. Please type: I UNDERSTAND THIS WILL DELETE RESOURCES"
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (GCS backend)
        run: |
          terraform -chdir="$DIR" init -input=false -reconfigure \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="prefix=gke/state"

      - name: Terraform Validate
        run: terraform -chdir="$DIR" validate

      - name: Terraform Plan (destroy)
        run: |
          terraform -chdir="$DIR" plan -destroy -input=false -out=tfplan.destroy \
            -var="project_id=${PROJECT_ID}" \
            -var="region=${REGION}" \
            -var="zone=${ZONE}" \
            -var="name=${NAME}"

      - name: Show Plan Summary
        run: terraform -chdir="$DIR" show -no-color tfplan.destroy | tee "$DIR/destroy-plan.txt"

      - uses: actions/upload-artifact@v4
        with:
          name: tf-destroy-plan
          path: |
            ${{ github.event.inputs.directory }}/tfplan.destroy
            ${{ github.event.inputs.directory }}/destroy-plan.txt

  apply:
    name: Apply (destroy)
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: production   # configure in repo Settings → Environments
    env:
      DIR:  ${{ github.event.inputs.directory }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (GCS backend)
        run: |
          terraform -chdir="$DIR" init -input=false -reconfigure \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="prefix=gke/state"

      - uses: actions/download-artifact@v4
        with:
          name: tf-destroy-plan
          path: ${{ github.event.inputs.directory }}

      - name: Terraform Apply (destroy)
        run: terraform -chdir="$DIR" apply -input=false -auto-approve tfplan.destroy

